name: Automerge2

on:
  push:
    branches:
    - release/**
    - main

jobs:
  automerge-branches:
    name: "Automerge branches"
    uses: github.com/LuisAntezana/test_repo/blob/main/.github/workflows/automerge2.yml@main
