name: Automerge2

on:
  push:
    branches:
    - release/**
    - main

jobs:
  automerge-branches:
    name: "Automerge branches"
    uses: LuisAntezana/test_repo/.github/workflows/automerge2.yml@main
